version: '3.8'

services:
  remnawave-shop:
    build: .
    restart: unless-stopped
    volumes:
      - ./app/data:/app/app/data
      - ./app/logs:/app/app/logs
    env_file:
      - .env
    depends_on:
      - remnawave-shop-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remnawave-shop.rule=Host(`${BOT_DOMAIN}`)"
      - "traefik.http.routers.remnawave-shop.entrypoints=websecure"
      - "traefik.http.routers.remnawave-shop.tls.certresolver=letsencrypt"
      - "traefik.http.services.remnawave-shop.loadbalancer.server.port=${BOT_PORT}"

  remnawave-shop-redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - remnawave-shop-redis-data:/data

  traefik:
    image: traefik:v3.0
    restart: unless-stopped
    command:
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - remnawave-shop-letsencrypt:/letsencrypt

volumes:
  remnawave-shop-redis-data:
  remnawave-shop-letsencrypt: